### ISSUE TITLE
pipeline reads only a single input fastq file

### ISSUE THREAD

**Issue by hesham123457887** [nf-core/smrnaseq#102]
Hi there!

I am running the pipeline to report differentially expressed miRNAs in C vs T samples. The pipeline works perfectly when I run it on a single input file, ex code below:
nextflow run ~/Downloads/smrnaseq/ -profile docker --protocol custom --input F1.fq.gz --outdir Results --genome GRCm38 --min_length 15 --trim_galore_max_length 50 --three_prime_adapter AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

I get the prediction of the novel and known miRNAs which is good. However, I need to run the pipeline on two input fastq files, C vs T, to report differentially expressed miRNAs. I placed the C and T fastq files in a single folder and used the below code to run it:
nextflow run ~/Downloads/smrnaseq/ -profile docker --protocol custom --input  *fq.gz* --outdir Results --genome GRCm38 --min_length 15 --trim_galore_max_length 50 --three_prime_adapter AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

I see that the pipeline only reads one of the fastq files, in this case C1.fq.gz. I wonder if I can specify multiple input fastq files so that the pipeline would report the differentially expressed miRNAs with edgeR?

Thx!

**Comment by hesham123457887** [comment]
I have another suggestion/inquiry please.. 
Is there a way to customize the input fastq files into C and T groups? 
The pipeline works very well for single fastq comparisons, ex: (C1.fq) vs (T1.fq).. Can it be further integrated with group of controls against a group of treatments, ex: (C1.fq C2.fq C3.fq) vs (T1.fq T2.fq T3.fq)? 
thx!

**Comment by apeltzer** [comment]
I made a new issue for your question - see #124 to keep this separate from your initial question you posted above.
