### ISSUE TITLE
[FEATURE] UMI Handling (extract, trimming, merging trimming reports)

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#114]
# nf-core/smrnaseq feature request

## Is your feature request related to a problem? Please describe

We have some data that has UMIs attached to the reads and would like to be able to both extract & trim these and have the reports of that step in the final report available as well. 

## Describe the solution you'd like

We have functional code to perform this using cutadapt + some extra scripts & would like to contribute this and/or consider a different / alternative solution if there is a better approach in doing this. 

## Describe alternatives you've considered

Doing this prior smrnaseq, but we figured its a more common use case and could be an optional addition to the pipeline.

**Comment by idot** [comment]
see also  #49

**Comment by apeltzer** [comment]
Closing in favour of #49
