### ISSUE TITLE
Error executing process > bowtie indices... mirBase issue?

### ISSUE THREAD

**Issue by hesham123457887** [nf-core/smrnaseq#118]
Hi there!

I used to run nf-core/smrnaseq and it worked like a charm until last week, when I had issues with the pipeline. I used the same command earlier:
nextflow run ~/Downloads/smrnaseq/ -profile docker --input '*fq.gz*' --outdir result --genome GRCm38 

Now, when I run the same command on the same dataset I get errors:
Error executing process bowtie indices..

Caused by:
  Can't stage file ftp://mirbase.org/pub/mirbase/CURRENT/mature.fa.gz -- reason: Connection refused (Connection refused)

Can you please let me know if there's an issue with mirbase datasets, or maybe something wrong that I overlooked? thx!

The pipeline gets stuck in the 'mirtrace' process with no progress for days..

**Comment by hesham123457887** [comment]
<!--
# nf-core/smrnaseq bug report

Hi there!

I used to run nf-core/smrnaseq and it worked like a charm until last week, when I had issues with the pipeline. I used the same command earlier:
nextflow run ~/Downloads/smrnaseq/ -profile docker --input '*fq.gz*' --outdir result --genome GRCm38 

Now, when I run the same command on the same dataset I get errors:
Error executing process bowtie indices..

Caused by:
  Can't stage file ftp://mirbase.org/pub/mirbase/CURRENT/mature.fa.gz -- reason: Connection refused (Connection refused)

Can you please let me know if there's an issue with mirbase datasets, or maybe something wrong that I overlooked? thx!

**Comment by hesham123457887** [comment]
.

**Comment by evchambers** [comment]
Hi @hesham123457887, I am also experiencing this issue. Seems to be a problem connecting to mirbase.

**Comment by hesham123457887** [comment]
> Hi @hesham123457887, I am also experiencing this issue. Seems to be a problem connecting to mirbase.

Yah.. couldn't really find a workaround. Did you mange to fix it?

**Comment by lpantano** [comment]
through the web page this is working, worst case they change the url and we need to update. you could pass the parameters pointing to the right file if this is the issue. i can check back tomorrow.

**Comment by hesham123457887** [comment]
> you could pass the parameters pointing to the right file if this is the issue.

Sure, which parameters then? Is it the --fasta one or something else should be joined in the command? thx!

**Comment by Shellfishgene** [comment]
I also noticed this, from Linux I get `connection refused` (with wget, curl and via smrnaseq), and Firefox downloads a 0 byte file with the ftp links. The download links on the website are https, not ftp as the pipeline tries, maybe this was changed recently.
The options for pointing to the already downloaded files are `--mature` and `--hairpin`.

**Comment by hesham123457887** [comment]
> The options for pointing to the already downloaded files are `--mature` and `--hairpin`.

Perfect... It runs now without the error.. Will see till the end thx!

P.S: For the mature and hairpin fa files, are those mouse, human, or a combined fasta file? 
I Couldn't find this info online.. thx

**Comment by evchambers** [comment]
@Shellfishgene thank you so much for this. Manually downloading the files and passing --hairpin and --mature has bypassed the problem.

@hesham123457887 I believe they are combined fasta files.

**Comment by Shellfishgene** [comment]
Changing the download links in the smrnaseq `nextflow.config` from the ftp version to
```
mature = "https://mirbase.org/ftp/CURRENT/mature.fa.gz"
hairpin = "https://mirbase.org/ftp/CURRENT/hairpin.fa.gz"
```
works also.

**Comment by ylcodiak** [comment]
> Changing the download links in the smrnaseq `nextflow.config` from the ftp version to
> 
> ```
> mature = "https://mirbase.org/ftp/CURRENT/mature.fa.gz"
> hairpin = "https://mirbase.org/ftp/CURRENT/hairpin.fa.gz"
> ```
> 
> works also.

I have the same issue. I am new to nextflow configure, I created a file name nextflow.config in my current directory, and used the above two lines in the file. it still have the same error.  I was using this line of code on command line: 
nextflow run nf-core/smrnaseq --reads data/*.gz -profile docker --genome 'GRCh38' -config nextflow.config.   Shellfishgene, would you mind sharing your configure file?

**Comment by apeltzer** [comment]
This should be addressed in the current `dev` branch now - so you may just run that version for now `-r dev` to get around the issue 👍🏻  

Release coming soon ™️ I suppose, but when looking at the current dev branch it looks like things should work for you when directly using the dev branch. 

Please re-open if this is not the case and/or open a new issue then 👍🏻
