### ISSUE TITLE
Update MultiQC to 1.12 planned release before releasing DSLv2 version

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#128]
This bug here is resolved in the upcoming MultiQC version 1.12 -- https://github.com/ewels/MultiQC/issues/1263 

It occurred to me when running the dev branch unfortunately, but is resolved. Before we attempt at doing a release of the new pipeline version, maybe we could have this fixed by upgrading to the latest MultiQC release?

**Comment by apeltzer** [comment]
As long as we don't forget, no worries 👍🏻

**Comment by apeltzer** [comment]
x-ref https://github.com/nf-core/modules/pull/1282

**Comment by lpantano** [comment]
can we closed this?

**Comment by apeltzer** [comment]
Yes absolutely!
