### ISSUE TITLE
Output for Differential micro-RNA analysis

### ISSUE THREAD

**Issue by rakeshponnala** [nf-core/smrnaseq#130]
I just did run ~170 microRNA samples using the version -r dsl2 successfully by supplying a sample sheet. In order for me to perform Differential expression analysis from mirDeep2, I don't see a consolidated file with miRNA read counts for all the samples, although I see individual CSV and HTML files for 170 samples from mirdeep2. Although, I see a single mirTop.tsv file..(known microRNA). 

How could I generate the consolidated file/ read counts for known/novel micro-RNA across all samples to proceed to statistical analysis from mirdeep2 ? Below is the command I used:

nextflow run nf-core/smrnaseq -r dsl2 --input 'sample.sheet.csv' -profile singularity --protocol qiaseq --fasta WholeGenomeFasta/genome.fa --mirtrace_species cfa --mirna_gtf cfa.gff3 --hairpin hairpin.fa --mature mature.fa -- --max_cpus 96 --max_memory 1400GB

**Comment by lpantano** [comment]
Hi @rakeshponnala, there is a discussion about how to do that in slack, but there is not straight forward answer. When I developed this in bcbio_nextgen. I pull all the samples together and run mirdeep2, then prepare files similar to mirbase to run the same tools used for known mirnas with the mirdeep2 novel microrna. But this is something to be implemented here right now, and it requires of some time of somebody.

**Comment by keenhl** [comment]
Hi @rakeshponnala 

This is something I would like to do also.   We would have to be careful about how we are merging overlaps across samples.  For example, below are some results I got from two different samples.   Probably is the same miRNA, but the coordinates are slightly different.  We probably want to merge these two together, but there might be other cases that are less clear what to do. 

1	137468744	137468827	novel:1_1627	2.3	-	137468744	137468827	0,0,255
1	137468745	137468826	novel:1_1821	2.3	-	137468745	137468826	0,0,255

**Comment by apeltzer** [comment]
There is work on the differentialabundance pipeline now starting which will support output from smrnaseq too - so people can just use a second pipeline to run DGE analysis.
