### ISSUE TITLE
Bug in multiqc / mirTop broke

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#137]
Had this unfortunately with the `dev` branch:

```
  /// MultiQC <U+1F50D> | v1.12

|           multiqc | Search path : /work/38/b3bd004777869168b75aaf74ee8d69
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 418/418
|    custom_content | software_versions: Found 1 sample (html)
|    custom_content | nf-core-smrnaseq-summary: Found 1 sample (html)
╭───────────────── Oops! The 'mirtop' MultiQC module broke... ─────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was:       │
│ ./full_mirtop_stats.log                                                      │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 65 │
│     output = mod()                                                           │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/modules/mirtop/mirto │
│     self.parse_mirtop_report(f)                                              │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/modules/mirtop/mirto │
│     parsed_data["read_count"] = parsed_data["isomiR_sum"] + parsed_data["ref │
│ KeyError: 'ref_miRNA_sum'                                                    │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|          samtools | Found 158 stats reports
|            fastqc | Found 79 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | Plots       : multiqc_plots
|           multiqc | MultiQC complete
|           multiqc | 1 flat-image plot used in the report due to large sample numbers
|           multiqc | To force interactive plots, use the '--interactive' flag.
See the documentation.
```

Not sure what is causing this, didN#t check the module so far. 

@ewels any idea?

**Comment by ewels** [comment]
Not sure sorry, I guess the output is different for some reason? Not seen it before, need to see the tool output. These things are usually fairly easy to patch though.

**Comment by apeltzer** [comment]
Hi @ewels  I have added some fake data (that resembles the original data very much) to add a testcase for `mirtop` mabye. See linked PR to testdata: https://github.com/ewels/MultiQC_TestData/pull/227 

@lpantano might also be interested in seeing this -- it looks like the `ref_miRNA_sum` variable is not present for all the samples here, which might explain that the access then fails.

**Comment by lpantano** [comment]
oh, I didn't think about not having that for all samples...that seems weird to be honest,  related to the data itself...no sequences matching the references seems weird. Thank for spotting this.

**Comment by apeltzer** [comment]
Considering that we likely need to address this upstream either in mirtop to enforce this is always there in the output _or_ in the multiqc module - can we potentially add a `--skip_mirtop` option to enable users to circumvent this bug for the time until this is fixed upstream? @JoseEspinosa @lpantano what do you think about that?

**Comment by JoseEspinosa** [comment]
Yes, might be a good solution for now. Should we skip the whole process or maybe only multiqc i.e. --skip_mirtop_multiqc ?

**Comment by lpantano** [comment]
I think the quantification is useful, I would prefer to skip the QC of multiqc in this case only if it were my data.

**Comment by lpantano** [comment]
I fixed that in mirtop, waiting for bioconda to bump the version, and then we need to update the docker container, that I forgot how to do it, so If somebody knows how, happy to get help here :)

**Comment by JoseEspinosa** [comment]
You mean the mulled container [here](https://github.com/nf-core/smrnaseq/blob/c90a5cde6553f599d1b5ed9d4aa2fadc741eee04/modules/local/mirtop_quant.nf#L4-L7) ? I can take care of it if you are referring to this

**Comment by JoseEspinosa** [comment]
Here is the PR in the biocontainers multi-package containers repository https://github.com/BioContainers/multi-package-containers/pull/2150

**Comment by JoseEspinosa** [comment]
Here is the PR with the updated container https://github.com/nf-core/smrnaseq/pull/143

**Comment by apeltzer** [comment]
All fine now 👍🏻

**Comment by apeltzer** [comment]
Hmm, unfortunately still an issue. I've had more projects with the same error :-(

**Comment by apeltzer** [comment]
It still looks like some samples are missing the same entry, e.g. `ref_miRNA_sum` is not present for all samples unfortunately. Thus the MultiQC module breaks --> crashing pipeline :-(

**Comment by gpalidwor** [comment]
Bug opened https://github.com/ewels/MultiQC/issues/1712

**Comment by apeltzer** [comment]
Maybe a good idea yeah to fix this in MultiQC, although that means we have to wait for MultiQC V1.13 to fix this 😢

**Comment by ewels** [comment]
![wait](https://media.giphy.com/media/l0HlBO7eyXzSZkJri/giphy.gif)

**Comment by lpantano** [comment]
Hi,
if you give me a gff file from mirtop that is missing that I can take a look. I know where the code is so I can pull a fix quickly. It is working for us, so I don't have any example.
Thanks!

**Comment by gpalidwor** [comment]
below is the gff file from the mirtop output in the results directory of the nf-core/smrna output. It's mostly zero counts because  it was a bad configuration, rerunning to see if multiqc succeeds with the proper config

[mirtop.gff.gaz]([mirtop.gff.gz](https://github.com/nf-core/smrnaseq/files/8968410/mirtop.gff.gz))

**Comment by ewels** [comment]
Yeah, MultiQC should never crash with a traceback like that. For starters it means that all subsequent logs from that tool will be ignored, so it should definitely be fixed 👍🏻

**Comment by apeltzer** [comment]
PR in modules is open https://github.com/nf-core/modules/pull/1814 , once this is merged, can upgrade the module for MultiQC here in the repository and we're fine again 👍🏻

**Comment by apeltzer** [comment]
MultiQC 1.13 is released, as such this should be fixable by upgrading to the MQC 1.13 module
