### ISSUE TITLE
Custom Genome rabbit

### ISSUE THREAD

**Issue by keenhl** [nf-core/smrnaseq#139]
Thanks for the nextflow pipeline.  I have just started to use it, and before going much farther, I wanted to find out about how to use the pipeline with a custom genome. Specifically, I am trying to do a srna analysis on Oryctolagus cuniculus - rabbit, which I didn't see in IGenomes.  

Thanks for your help.

**Comment by keenhl** [comment]
I know how to fix this now.  I just need to manually download the  files for --hairpin, --mature, --fasta, and --mirna_gtf. 

mature and hairpin

https://www.mirbase.org/ftp/CURRENT/mature.fa.gz
https://www.mirbase.org/ftp/CURRENT/hairpin.fa.gz

mirbase annotation

https://www.mirbase.org/ftp/CURRENT/genomes/

genome fasta

http://ftp.ensembl.org/pub/release-100/fasta/

**Comment by OliverH96** [comment]
Hello, I'm currently facing a similar problem trying to use the pipeline with a custom sheep genome. There is not currently a mirbase annotation gff3 file for sheep available for download from miRBase, and from what I can see there doesn't seem to be one for rabbit too (looking for ocu.gff3).
How did you get around this problem?
