### ISSUE TITLE
Low mapping to the reference genome: is it expect for non-coding RNAs?

### ISSUE THREAD

**Issue by MargheritaSq** [nf-core/smrnaseq#153]
Hi all!

I have recently used this pipeline for the analysis of my data but I am concerned about the low mapping results. I attached the Alignment bar plot to this message to clarify this my point. Despite using the right adapters (qiaseq) and knowing that the fastq sequences I have analyzed were already purified from the UMI sequences, I have obtained between 0.2 and 0.5% of mapping to the reference mouse genome. I have compared this plot to the test (pipeline test) one and they look similar. Therefore I am wondering if this low mapping percentages can be considered an expected result, since we are analysing non coding RNAs, a small amount with respect to the mRNAs.
![samtools_alignment_plot-1](https://user-images.githubusercontent.com/74371672/169304425-f064651e-c0f8-44b7-ae2b-0bc513816a85.png)

**Comment by MargheritaSq** [comment]
Thanks!

Marghe

**Comment by MargheritaSq** [comment]
Hi there!

I have post my issue about 2 month ago and I did not receive any answer to my question. I JUST want to know if it is "standard/normal" to obtain a low mapping quality from the analysis of this type of data. Thank you. Cheers

**Comment by jonoave** [comment]
Hi @MargheritaSq, 

I've used this pipeline and our mapping rate was between 3-12%, so some of your samples look pretty high up to 20%. We we also initially skeptical about the low mapping rate. So we tried it on a public dataset that had a published paper and we got around 10% mapping rate, comparable to the paper. 

Hope this helps.

**Comment by MargheritaSq** [comment]
> 

Thank you very much for your reply. It helped a lot!
