### ISSUE TITLE
trimmed output not as documented

### ISSUE THREAD

**Issue by gpalidwor** [nf-core/smrnaseq#161]
### Description of the bug

Using smrnaseq v2.0.0, I see this with the example minimal dataset output, it's also the case in the AWS output.

The documentation says trimming will go into results/trim_galore, but it goes into results/trimmed. As well the trimmed directory does not contain the trimmed fastq.gz output as documented.

**Comment by apeltzer** [comment]
Looking at this here - https://github.com/nf-core/smrnaseq/blob/4278785edd4a5e2cf5e599e7eb4daa133e4983b9/conf/modules.config#L111 I think the `*.{txt,fastq.gz}` pattern should be enough to fix this . Will do this in `dev` now.
