### ISSUE TITLE
--mirtrace_protocol arguments redundant, --protocol only should be sufficient

### ISSUE THREAD

**Issue by gpalidwor** [nf-core/smrnaseq#168]
### Description of feature

Currently smrna requires both --protocol and --mirtrace_protocol to be set.  Both default to illumina. If --protocol is set to a non illumina value (e.g. nextflex)  --mirtrace_protocol must be set to the same. As such the --mirtrace_protocol argument is redundant and can lead to confusing results if not set to match --protocol. I can think of no cases where  --protocol and --mirtrace_protocol should be different

**Comment by gpalidwor** [comment]
Thanks for looking at it; My experience was the mirTrace output was not meaningful (didn't map to anything) for ` --protocol nextflex` until I also set `--mirtrace_protocol nextflex` so perhaps it's protocol specific..?

**Comment by apeltzer** [comment]
Fixed in dev
