### ISSUE TITLE
create TEMPLATE branch

### ISSUE THREAD

**Issue by lpantano** [nf-core/smrnaseq#17]
hi,

This is the template I have in my branch done with nf-core 1.6. Should I just push the TEMPLATE branch to the smrnaseq pipeline since there is no branch right now?

https://github.com/lpantano/smrnaseq/tree/TEMPLATE

**Comment by apeltzer** [comment]
Yes! You could do that, to get this going! Thanks a bunch for working on this!

**Comment by lpantano** [comment]
ok! done: https://github.com/nf-core/smrnaseq/tree/TEMPLATE

**Comment by drpatelh** [comment]
Based on what it says here: https://nf-co.re/developers/sync
"Follow the prompts to fill in the pipeline name, description and author(s). Make sure that you take the exact text that you already have already used in your pipeline's nextflow.config file (manifest.name etc.), if these have already been written."

In `nextflow.config`, the `manifest.author` and `manifest.description` fields arent the same in the `TEMPLATE` and `dev` branches at the moment. Im assuming that will matter when the pipeline is auto-created by the `template-bot`?

Maybe the easiest thing to do is to create a PR to the `TEMPLATE` branch and make those fields the same?

From the last few PRs it seems like the pipeline is working @lpantano ? Im just thinking it may be worth doing another PR after that from `dev` to `master` to update all of the all code with the new template.

**Comment by drpatelh** [comment]
I believe you have done this now :+1:
