### ISSUE TITLE
--protocol sequence not passed to mirtrace?

### ISSUE THREAD

**Issue by JanineRoy** [nf-core/smrnaseq#172]
### Description of the bug

We have data created using QIASEQ protocol. 
When setting --protocol "qiaseq" and investigating mirtrace QC output, no adapter got removed. 
Output from mirtrace:
![image](https://user-images.githubusercontent.com/109286724/178975911-280a27d6-b9f0-44a0-875a-dbe635903e12.png)
but mirtop creates a file with many mirna counts.

Nevertheless, when directly stating --three_prime_clip_r1 0 --clip_r1 0 --three_prime_adapter "AACTGTAGGCACCATCAAT" (please not that this is the same sequence as in the --protocol "qiaseq"), mirtrace is able to remove adapter:
![image](https://user-images.githubusercontent.com/109286724/178976252-8beaf41f-fe9a-4f38-8a68-426ea76412c2.png)
but then the downstream analysis breaks (mirtop, MULTIQC).
The above also only works, when I do not state --protocol "custom", otherwise mirtrace breaks. Seems like there is no "custom" defined in mirtrace.

maybe related  to?
#168 

### Command used and terminal output

```console
# this lets mirtrace remove adapter, but mirtope and multiQC fail
nextflow run nf-core/smrnaseq -profile bi,cluster --input smRNASeq_input_test.csv \
--outdir 00_test_smRNAseq_qiaseq_as_custom/ --genome GRCh38 -r dev --mirtrace_species "hsa"  \
--skip_mirdeep \
--three_prime_clip_r1 0 --clip_r1 0 --three_prime_adapter "AACTGTAGGCACCATCAAT"

# this lets mirtop create a good looking result, but mirtrace is not able to remove adapters
nextflow run nf-core/smrnaseq -profile bi,cluster --input smRNASeq_input_test.csv \
--outdir 00_test_smRNAseq_qiaseq/ \
--genome GRCh38 -r dev --mirtrace_species "hsa" --protocol "qiaseq" --skip_mirdeep
```

### System information

Nextflow version 22.04.0

**Comment by apeltzer** [comment]
Fixed in `dev`
