### ISSUE TITLE
Per-sample adapter sequence definition

### ISSUE THREAD

**Issue by robsyme** [nf-core/smrnaseq#191]
### Description of feature

At the moment, we auto-detect adapter sequence in each sample independently. This allows us to accomodate runs that are a mixture of different adapters. 

If we know the adapter sequence ahead of time, we can only specify a single adapter sequence that is uniformly applied to all samples. It would be nice to be able to (optionally) supply adapter sequences on a per-sample basis - perhaps as an extra column in the samplesheet.

**Comment by apeltzer** [comment]
Currently after brainstorming for a bit, we do not see the need for this as mostly the analysis will be either a single batch (with the same adapter) or even mutliple batches with the same prep --> thus not really something we have to focus on right now.
