### ISSUE TITLE
mirTrace Adapter 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#196]
### Description of the bug

Looks like the adapter sequence found by fastp isn't ending up correctly in mirtrace, e.g. the mirtrace.json says this:

![image](https://user-images.githubusercontent.com/2359510/195624992-46641710-035b-4aaa-9e84-aafd1a7747f5.png)

While it should say this:

```
java -Xms38654705664 -Xmx38654705664 -jar $mirtracejar/mirtrace.jar --mirtrace-wrapper-name mirtrace qc  \
    --species hsa \
    --adapter AGATCGGAAGAGCACACGTCTGAACTCCAGTCA \
     \
    --config mirtrace_config \
    --write-fasta \
    --output-dir mirtrace \
    --force
```

Maybe something weird is happening here - should we add " " around the adapter sequence maybe?  
Also adding @robsyme to the discussion ;-)

**Comment by bounlu** [comment]
That's OK. `miRTrace` shortens the adapter to 8 characters. Since anything after that is also trimmed away from the 3' end of the reads, the result is the same.

**Comment by apeltzer** [comment]
Ok - thanks @bounlu
