### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by FanBioinformatics** [nf-core/smrnaseq#216]
### Description of the bug

I got this error complaining the process of SAMPLESHEET_CHECK; however, when I download the actually .py file from GitHub and run it locally, it runs just fine. Please help.

### Command used and terminal output

```console
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/smrnaseq] Pipeline completed with errors-
Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)` terminated with an error exit status (1)

Command executed:

  check_samplesheet.py \
      samplesheet.csv \
      samplesheet.valid.csv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  standard_init_linux.go:178: exec user process caused "exec format error"

Work dir:
  /gpfs/mongo/data/hfan1/venu_20221021_RNAseq/fastq/work/b6/4f1ddcbad3549b0387cb26aa39af04

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### System information

NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME=RHEL
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

**Comment by apeltzer** [comment]
Can you run any test profile and are you by any chance running with singularity? that sounds like an issue with singualrity...

**Comment by FanBioinformatics** [comment]
Test run runs into error right away as well. I am using docker. The only
thing I can think of is the architecture of images downloaded and the
architecture of our Linux server is not compatible?

**Comment by apeltzer** [comment]
Potentially possible - but your system looks like a standard AMD64 / x86 system so not sure this is really the reason. Can you run any other pipeline from nf-core using the standard tests, e.g. `nextflow run nf-core/rnaseq -profile test,docker` ?

**Comment by FanBioinformatics** [comment]
My system says 3.10.0-957.el7.ppc64le though.
I can not test-run any of the pipelines on our linux server.

From: Alexander Peltzer ***@***.***>
Date: Wednesday, December 21, 2022 at 10:14 AM
To: nf-core/smrnaseq ***@***.***>
Cc: Huihui.Fan ***@***.***>, Author ***@***.***>
Subject: Re: [nf-core/smrnaseq] standard_init_linux.go:178: exec user process caused "exec format error" (Issue #216)

Potentially possible - but your system looks like a standard AMD64 / x86 system so not sure this is really the reason. Can you run any other pipeline from nf-core using the standard tests, e.g. nextflow run nf-core/rnaseq -profile test,docker ?

**Comment by apeltzer** [comment]
.ppc64le --> PowerPC architecture. That means the images we have won't work for you as this is not an X86/AMD64 architecture.

**Comment by FanBioinformatics** [comment]
That was my guess as well. Is there any way to work around this? Our IT is not of much help with this issue.

From: Alexander Peltzer ***@***.***>
Date: Wednesday, December 28, 2022 at 8:23 AM
To: nf-core/smrnaseq ***@***.***>
Cc: Huihui.Fan ***@***.***>, Author ***@***.***>
Subject: Re: [nf-core/smrnaseq] standard_init_linux.go:178: exec user process caused "exec format error" (Issue #216)

.ppc64le --> PowerPC architecture. That means the images we have won't work for you as this is not an X86/AMD64 architecture.

**Comment by apeltzer** [comment]
Not really - we are using biocontainers for most of our pipelines, there is no PPC support for these platforms unfortunately :-(
