### ISSUE TITLE
mirTrace uses fastq name, not sample name

### ISSUE THREAD

**Issue by drejom** [nf-core/smrnaseq#220]
### Description of the bug

In the mirTrace output folder and in the mirTrace sections of the MultiQC report, files are labeled by the fastq basename rather than the sample name indicated in the sample sheet, as for other tools.

Maybe something around here?
https://github.com/nf-core/smrnaseq/blob/27514c40c08d1eab8249521096f4f2f7be875104/modules/local/mirtrace.nf#L32-L35

Should `prefix=${meta.id}` ?? 

### System information

nf-core/smrnaseq v2.1.0

**Comment by apeltzer** [comment]
Good spot - if you feel keen to make a PR to fix this towards `dev`, happy to review. Otherwise will take care in the next weeks, hopefully getting a couple of bugs squished for a patch release 👍🏻

**Comment by apeltzer** [comment]
Fixed in #223
