### ISSUE TITLE
Fastp process outputs everything to log file

### ISSUE THREAD

**Issue by lcabus-flomics** [nf-core/smrnaseq#226]
### Description of the bug

The fastp process outputs everything to a log file. This is problematic in some cases, such as when running the pipeline with AWS, where the log files are catched with CloudWatch and it can generate huge costs (>100€ for 100 samples).

It could be solved by removing the `--stdout` line in the fastp module and not emitting the log file.

### System information

Nextflow 22.10.4
Executor awsbatch
Docker
Linux
nf-core/smrnaseq 2.1.0

**Comment by apeltzer** [comment]
Can you investigate if this behaviour is still the same for `dev` ?

**Comment by apeltzer** [comment]
Yeah I'll fix this upstream  -- see PR in modules, once this is done will fix in #227 by upgrading to the latest module. The logfile we would like to keep as this is only large in cases where the `--stdout` is used and in regular cases negligibly small (few kbs / sample) and used for metric generation. I will ping some of the authors of the fastp module to confirm that this doesn't break things.

**Comment by apeltzer** [comment]
Thanks @lcabus-flomics for investigating / reporting !

**Comment by lcabus-flomics** [comment]
No problem, happy to help :)

**Comment by apeltzer** [comment]
Hi @lcabus-flomics  - please use `-r update-modules` and test again 👍🏻

**Comment by lcabus-flomics** [comment]
Yes, it worked correctly. I will now close the issue, thank you very much!
