### ISSUE TITLE
three_prime_adapter parameter was null

### ISSUE THREAD

**Issue by ray1919** [nf-core/smrnaseq#229]
### Description of the bug

I tested in v2.1.0 and current dev branch.

No matter I set **protocol** to qiaseq or **three_prime_adapter** to sepcific seq, the **fastp** did not use expected adater sequence. 

When hard code the fastp --adapter-sequence to $params.three_prime_adapter, the error log showed the $params.three_prime_adapter variable is **null**.

I tried to debug it , but was puzzled. Hope you could help me.

### System information

Nextflow version 22.10.6
Hardware Cluster
Executor lsf
Container engine: Local
OS Linux centos
Version of nf-core/smrnaseq 2.1.0, dev

**Comment by apeltzer** [comment]
Should be fine in dev
