### ISSUE TITLE
illumina protocol clip parameters

### ISSUE THREAD

**Issue by bounlu** [nf-core/smrnaseq#237]
The default parameters for illumina protocol denote clipping bases from reads [here](https://github.com/nf-core/smrnaseq/blob/5ce052d93d4363c3d16667cc757948fa5ce2c763/lib/WorkflowSmrnaseq.groovy#L82-L83). This was not the case before the last updates. Is this correct?

                params.putIfAbsent("clip_r1", 1);
                params.putIfAbsent("three_prime_clip_r1",2);

 or it should be:

                params.putIfAbsent("clip_r1", 0);
                params.putIfAbsent("three_prime_clip_r1",0);

**Comment by lpantano** [comment]
mm, l thought Illumina didn't need any clipping. I am not sure how it ended up there.

**Comment by lpantano** [comment]
@robsyme seems to be the last one to change [this](https://github.com/nf-core/smrnaseq/commit/47a8ebd90922ca11e0d3116641cea765a725f055).

**Comment by apeltzer** [comment]
Addressed in 2.3.0 release, closing this therefore 👍🏻
