### ISSUE TITLE
depot.galaxyproject.org-singularity-fastp-0.23.2--h79da9fb_0.img: image format not recognized

### ISSUE THREAD

**Issue by JiahuaQu** [nf-core/smrnaseq#261]
### Description of the bug

I ran the smrnaseq pipeline in our institute's HPC and had the error:
The exit status of the task that caused the workflow execution to fail was: 255.
depot.galaxyproject.org-singularity-fastp-0.23.2--h79da9fb_0.img: image format not recognized
Details in the attachment.
[error.txt](https://github.com/nf-core/smrnaseq/files/12028398/error.txt)

I have downloaded the sigularity and all images, and chmod to 777.

### System information

nextflow 23.04.2 build 5870
HPC
SGE
Singularity
CentOS
dev: When downloading, only the first option, dev, could be downloaded.

Hope get your help. Thank you very much.

**Comment by apeltzer** [comment]
Please rerun with `dev` - this should repull the image. Seems like the download didn't work.
