### ISSUE TITLE
merging fastq unnecessarily

### ISSUE THREAD

**Issue by bounlu** [nf-core/smrnaseq#268]
[This](https://github.com/nf-core/smrnaseq/blob/f7022abd9fc1a6db6f4ca114c17368dbbe8ca4f8/modules/nf-core/cat/fastq/main.nf#L25) line and [this](https://github.com/nf-core/smrnaseq/blob/f7022abd9fc1a6db6f4ca114c17368dbbe8ca4f8/modules/nf-core/cat/fastq/main.nf#L56) line are not identical.

Similarly, [this](https://github.com/nf-core/smrnaseq/blob/f7022abd9fc1a6db6f4ca114c17368dbbe8ca4f8/modules/nf-core/cat/fastq/main.nf#L36) and [this](https://github.com/nf-core/smrnaseq/blob/f7022abd9fc1a6db6f4ca114c17368dbbe8ca4f8/modules/nf-core/cat/fastq/main.nf#L67) for pair-end.

`FASTQ` files are unnecessarily merged even though they are not coming from multiple lanes. Basically it's just renaming rather than merging. This should be avoided as in the stub.

**Comment by apeltzer** [comment]
Mind making a PR against `dev` ?

**Comment by apeltzer** [comment]
This is outdated and the module was updated already.
