### ISSUE TITLE
Number of cpu is not adapted for fastp tool

### ISSUE THREAD

**Issue by mAGLAVE** [nf-core/smrnaseq#270]
### Description of the bug

Hello,
The number of cpu for fastp is not adapted. The `--thread` option is for worker threads only. Not for all threads used by the tool.

https://github.com/OpenGene/fastp/issues/169:

> `--thread 2` means use 2 processing worker threads.
> Besides the worker threads, fastp uses one master thread, one loader thread, and one or two writer thread (depends on SE or PE).

So it should be `--thread (( $task.cpus - 3 ))` in nf-core-smrnaseq/2.2.1/modules/nf-core/fastp/main.nf, line 42.

**Comment by apeltzer** [comment]
This is actually something we should address upstream in https://github.com/nf-core/modules

**Comment by mAGLAVE** [comment]
ok, I'm going to do that. Thank you!
