### ISSUE TITLE
MIRDEEP2_RUN fails on GRCh38 due to whitespaces

### ISSUE THREAD

**Issue by davidecarlson** [nf-core/smrnaseq#273]
### Description of the bug

The MIRDEEP2_RUN process fails on all samples when using the GRCh38 version of the human genome fasta file (downloaded from igenomes) due to white spaces present in the fasta headers.

### Command used and terminal output

```console
nextflow \
run \
nf-core/smrnaseq \
--input samplesheet.csv \
--protocol "illumina" \
--fasta /gpfs/projects/GenomicsCore/indexes/GRCh38/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa \
--bowtie_index /gpfs/projects/GenomicsCore/indexes/GRCh38/Homo_sapiens/NCBI/GRCh38/Sequence/BowtieIndex \
--mirna_gtf /gpfs/projects/GenomicsCore/nf-core/smrnaseq/Acosta-Martinez/gff/hsa.gff3 \
--mirtrace_species hsa \
--mature /gpfs/projects/GenomicsCore/nf-core/smrnaseq/Acosta-Martinez/fastas/mature.fa \
--hairpin /gpfs/projects/GenomicsCore/nf-core/smrnaseq/Acosta-Martinez/fastas/hairpin.fa \
-profile seawulf \
--outdir smrnaseq_out

...
# run log

#####################################
#                                   #
# miRDeep2.0.1.3                   #
#                                   #
# last change: 08/11/2019           #
#                                   #
#####################################

miRDeep2 started at 15:7:13


#Starting miRDeep2
/usr/local/bin/miRDeep2.pl RSB487-02_collapsed.fa genome.fa RSB487-02_reads_vs_refdb.arf mature.fa_igenome.fa_idx.fa none hairpin.fa_igenome.fa_idx.fa -d -z _RSB487-02_collapsed

miRDeep2 started at 15:7:13


mkdir mirdeep_runs/run_30_08_2023_t_15_07_13_RSB487-02_collapsed

#Starting miRDeep2
Error: Genome file genome.fa has not allowed whitespaces in its first identifier
```

### Relevant files

[nextflow.log](https://github.com/nf-core/smrnaseq/files/12479427/nextflow.log)

### System information

Nextflow 23.04.2
Hardware: HPC
Executor: Slurm
Container: Singularity
OS: Rocky Linux 8
smrnaseq version: 2.2.1

**Comment by davidecarlson** [comment]
I should add that the pipeline completed despite these errors, but I presume MIRDEEP2_RUN is not supposed to fail.

**Comment by tijeco** [comment]
it looks like this has been raised in the MIRDEEP2 repo (https://github.com/rajewsky-lab/mirdeep2/issues/107), in which the response was 
>Just change the FASTA file before running miRDeep2.

Perhaps a simple thing like `awk '{print $1} genome.fa > one_column_genome.fa'` in the `MIRDEEP2_RUN` process would fix that?

**Comment by davidecarlson** [comment]
Thanks.  That's what I ended up doing.

Dave
