### ISSUE TITLE
Missing output folders

### ISSUE THREAD

**Issue by andrewdchen** [nf-core/smrnaseq#285]
### Description of the bug

The pipeline on my data ran successfully but I'm missing several results folders including edgeR.

Currently I only have the output folders:
```
fastp
genome
index
pipeline_info
```

I'm only skipping fastqc and multiqc in the pipeline command.
Seems like the [awsmegatests](https://nf-co.re/smrnaseq/2.2.3/results/) are also missing a couple of output folders.

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq \
    -r 2.2.3 \
    -profile singularity \
    --input clean_samplesheet.csv \
    --skip_fastqc \
    --skip_multiqc \
    --genome 'GRCh37' \
    --mirtrace_species 'hsa' \
    --protocol 'illumina' \
    --outdir 'Processed'
```

### System information

Nextflow version: 23.04.1
Hardware: HPC
Executor: Sun Grid Engine
Container engine: Singularity
OS: AlmaOS 8 Linux
Version of nf-core/smrnaseq: v2.2.3-g18d6c84

**Comment by apeltzer** [comment]
Dev should be fine now
