### ISSUE TITLE
The error with mirtrace

### ISSUE THREAD

**Issue by scabfle2** [nf-core/smrnaseq#286]
### Description of the bug

![image](https://github.com/nf-core/smrnaseq/assets/128769147/1b0b5f91-3006-4944-97b2-367f3725b65e)

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq --input ./config/samplesheet.csv --outdir ./nf_results --genome GRCh37 -profile docker
```

### System information

Nextflow  version 23.04.3
Hardwre HPC
Executor local
Container engine Docker
OS Linux
nf-core/smrnaseq v2.2.3-g18d6c84

**Comment by kvn95ss** [comment]
Check if docker is installed and configured correctly. Try running ```docker run hello-world```, if it doesn't work then set up your docker.

**Comment by apeltzer** [comment]
Yeah looks like a docker issue, the container is available online.
