### ISSUE TITLE
Unable to get bioconda::bowtie=1.3.1-4 from bioconda

### ISSUE THREAD

**Issue by Dane-Z** [nf-core/smrnaseq#292]
### Description of the bug

Hi I'm unable to get bioconda::bowtie=1.3.1-4 when trying to run the test data.
 
 

### Command used and terminal output

```console
$ nextflow run nf-core/smrnaseq -profile test,conda --outdir /gpfs/Cores/GSC/share/05_Scripts/nf-core
```

### Relevant files
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:INDEX_GENOME'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /gpfs/Cores/GSC/share/05_Scripts/nf-core/work/conda/env-828352f405d9a6398243f65dc3e2f943 bioconda::bowtie=1.3.1-4
  status : 1
  message:
    /gpfs/ri/shared/modules7/miniconda3/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
      warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
    
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - bioconda::bowtie=1.3.1-4
    
    Current channels:
    
      - https://conda.anaconda.org/bioconda/linux-64
      - https://conda.anaconda.org/bioconda/noarch
      - https://conda.anaconda.org/conda-forge/linux-64
      - https://conda.anaconda.org/conda-forge/noarch
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.

 -- Check '.nextflow.log' file for details
 
 
[nextflow.log](https://github.com/nf-core/smrnaseq/files/12770451/nextflow.log)

### System information

nextflow version 23.04.03
HPC
Conda
Linux

**Comment by Dane-Z** [comment]
I was able to fix this, but got a new similar bug, by changing the config order to conda-forge, bioconda, default. However, now I'm getting a different error: 

'''
PackagesNotFoundError: The following packages are not available from current channels:
    
      - bioconda::fastx_toolkit=0.0.14-9
    
    Current channels:
    
      - https://conda.anaconda.org/conda-forge/linux-64
      - https://conda.anaconda.org/conda-forge/noarch
      - https://conda.anaconda.org/bioconda/linux-64
      - https://conda.anaconda.org/bioconda/noarch
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.



 -- Check '.nextflow.log' file for details
'''

**Comment by apeltzer** [comment]
Try the latest branch `-r umi-handling`, this should be fine in that one. If not, please reopen the issue.
