### ISSUE TITLE
Migrate badge to travis-ci.com

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#30]
We've been migrating this over to travis-ci.com (as all travis-ci.org repositories will be shutdown at some point). Please update the badge in the readme accordingly :-)

**Comment by lpantano** [comment]
mm, I see the link to be pointing to `.com` in the README, is this in other place I cannot find? sorry.

**Comment by apeltzer** [comment]
Yeah everything else will be coming in via the TEMPLATE sync. 

I just opened this everywhere where we migrated over from Travis-Ci.org to Travis-Ci.com, so nevermind then 👍
