### ISSUE TITLE
Nextflex paired-end sequencing

### ISSUE THREAD

**Issue by sav0016** [nf-core/smrnaseq#323]
Hello,

I am trying to run nextflex 150bp paired end data. If I use only R1 so it works. I am not able to pass with both reads.
Thanks.

`N E X T F L O W  ~  version 23.10.1
Launching `/home/data3/.nextflow/assets/nf-core/smrnaseq/main.nf` [loving_dijkstra] DSL2 - revision: baab1a8371
WARN: Running with Protocol nextflex
WARN: Therefore using Adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
WARN: Clipping 4 bases from R1
WARN: And clipping 4 bases from 3' end
WARN: Access to undefined parameter `monochromeLogs` -- Initialise it to a default value eg. `params.monochromeLogs = some_value`

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/smrnaseq v2.3.0
------------------------------------------------------
Core Nextflow options
  runName         : loving_dijkstra
  containerEngine : docker
  launchDir       : /data3/data3/smrnaseq/nextflex/24-03-04/paired
  workDir         : /data3/data3/smrnaseq/nextflex/24-03-04/paired/work
  projectDir      : /home/data3/.nextflow/assets/nf-core/smrnaseq
  userName        : user
  profile         : docker
  configFiles     :

Input/output options
  input           : samplesheet.csv
  protocol        : nextflex
  outdir          : ./results

Reference genome options
  genome          : hg38
  mirtrace_species: hsa
  fasta           : s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/smrnaseq for your analysis please cite:

* The pipeline
  10.5281/zenodo.3456879

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/smrnaseq/blob/master/CITATIONS.md
------------------------------------------------------
WARN: Access to undefined parameter `fasta` -- Initialise it to a default value eg. `params.fasta = some_value`
[37/add4b7] Submitted process > NFCORE_SMRNASEQ:CAT_FASTQ (S16)
[5e/5ef3d1] Submitted process > NFCORE_SMRNASEQ:CAT_FASTQ (S15)
[a6/4f3839] Submitted process > NFCORE_SMRNASEQ:CAT_FASTQ (S14)
[84/5eda58] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTQC_RAW (S15)
[5d/dec972] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP (S15)
Staging foreign file: https://mirbase.org/download/mature.fa
Staging foreign file: https://mirbase.org/download/hairpin.fa
[d5/fe266e] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTQC_RAW (S14)
[cd/ff36f6] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP (S14)
[30/8e67a3] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:PARSE_HAIRPIN
[b8/34359a] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:PARSE_MATURE
[98/b3083e] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTQC_RAW (S16)
[9f/0f269a] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP (S16)
[41/6535e3] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:FORMAT_HAIRPIN (hairpin.fa_igenome.fa)
[21/91aa97] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:FORMAT_MATURE (mature.fa_igenome.fa)
[47/b9444c] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:INDEX_HAIRPIN
[74/ee88fa] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:INDEX_MATURE
[37/61d751] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (S15_seqcluster)
[55/80b48c] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTQC_TRIM (S15)
[c5/1eb7a3] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:BOWTIE_MAP_MATURE (S15_mature)
[43/6100f2] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (S14_seqcluster)
[bc/d58e24] Submitted process > NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTQC_TRIM (S14)
[27/b4a18c] Submitted process > NFCORE_SMRNASEQ:MIRNA_QUANT:BOWTIE_MAP_MATURE (S14_mature)
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (S15_seqcluster)'

Caused by:
  Process `NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (S15_seqcluster)` terminated with an error exit status (2)

Command executed:

  seqcluster collapse -f S15_1.fastp.fastq.gz S15_2.fastp.fastq.gz -m 1 --min_size 15 -o collapsed
  gzip collapsed/*_trimmed.fastq
  mkdir final
  mv collapsed/*.fastq.gz final/.

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES":
      seqcluster: $(echo $(seqcluster --version 2>&1) | sed 's/^.*seqcluster //')
  END_VERSIONS

Command exit status:
  2

Command output:
  Probably this will fail, you need bcbio-nextgen for many installation functions.
  ['collapse', '-f', 'S15_1.fastp.fastq.gz', 'S15_2.fastp.fastq.gz', '-m', '1', '--min_size', '15', '-o', 'collapsed']

Command error:
  Probably this will fail, you need bcbio-nextgen for many installation functions.
  ['collapse', '-f', 'S15_1.fastp.fastq.gz', 'S15_2.fastp.fastq.gz', '-m', '1', '--min_size', '15', '-o', 'collapsed']
  usage: seqcluster [-h] [--version] {collapse} ...
  seqcluster: error: unrecognized arguments: S15_2.fastp.fastq.gz

Work dir:
  /data3/data3/smrnaseq/nextflex/24-03-04/paired/work/37/61d751b11bc2b8374a17fd33ab8838

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/smrnaseq] Pipeline completed with errors-
`

**Comment by lpantano** [comment]
Hi, that is correct, the protocol for small-RNAseq is single end. Can you tell us more about your samples? are they expected to be sequences < 40nts? or they are expected to be in the 100 to 200nt long? Normally the sequencing protocols is targeting miRNAs (mainly), what was the intention of your experiment, if you cans share?

**Comment by sav0016** [comment]
@lpantano thank you for your answer!
We normally sequence our samples paired-end 150bp. smrnaseq works great using the first read only. Yes, we are targeting miRNA so inserts are small. So the conclusion is just to ignore R2 and use only R1, right? Not merge them somehow ...

**Comment by lpantano** [comment]
Yes, that should work! thank you!
