### ISSUE TITLE
umi qiaseq

### ISSUE THREAD

**Issue by genesandbones** [nf-core/smrnaseq#324]
### Description of the bug

I'm getting an error using the umi tools for a 2x100 qiaseq library.
The error is this: `ValueError: barcode regex(es) do not include any umi groups (starting with 'umi_') regex.Regx('=', flags=regex.v0), None`
![image](https://github.com/nf-core/smrnaseq/assets/38194037/84f120f2-e906-4390-9e02-b9ddd1b73c5b)

I suspect this is because the qiaseq library is not setup on a sequencer to include any base masking and so therefore the UMI's are not added into the header, which as I understand, is what the umi_ is looking for.

My current command is this: `--with_umi --umitools_extract_method regex --umitools_bc_pattern = ".+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12}).+" ` which is the command I have found in #49 

I'm looking for help either writing the regex differently as a workaround or if there is something wrong with the umi handling. Thanks!

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq -profile docker -r 2.3.0 -c ${inputConfig} --input ${inputFile} --with_umi --umitools_extract_method regex --umitools_bc_pattern = '.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)' --outdir "." -work-dir './work/'


Execution cancelled -- Finishing pending tasks before exit
-[nf-core/smrnaseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:UMITOOLS_EXTRACT (BS898-test-umi)'

Caused by:
  Process `NFCORE_SMRNASEQ:UMITOOLS_EXTRACT (BS898-test-umi)` terminated with an error exit status (1)

Command executed:

  umi_tools \
      extract \
      -I BS898-test-umi.umi_dedup.sorted.fastq.gz \
      -S BS898-test-umi.umi_extract.fastq.gz \
      --extract-method=regex --bc-pattern='=' \
      > BS898-test-umi.umi_extract.log
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:UMITOOLS_EXTRACT":
      umitools: $( umi_tools --version | sed '/version:/!d; s/.*: //' )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Matplotlib created a temporary cache directory at /tmp/matplotlib-vl6x_rga because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Traceback (most recent call last):
    File "/usr/local/bin/umi_tools", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.9/site-packages/umi_tools/umi_tools.py", line 61, in main
      module.main(sys.argv)
    File "/usr/local/lib/python3.9/site-packages/umi_tools/extract.py", line 335, in main
      extract_cell, extract_umi = U.validateExtractOptions(options)
    File "/usr/local/lib/python3.9/site-packages/umi_tools/Utilities.py", line 1177, in validateExtractOptions
      raise ValueError("barcode regex(es) do not include any umi groups "
  ValueError: barcode regex(es) do not include any umi groups (starting with 'umi_') regex.Regex('=', flags=regex.V0), None
```

### Relevant files

/*
 * -------------------------------------------------
 *  Nextflow standard config file for smRNAseq
 * -------------------------------------------------
 * Defines bundled input files and tools required
 * to run a pipeline
 * 
 *
 */

params {
	config_profile_name = 'name'
	config_profile_description = 'nf-core smRNAseq profile'
	max_memory = '120GB'
	max_cpus = 30
	max_time = '24.h'
	cleanup = true

	mirtrace_species = "hsa"
	mirna_gtf = "/home/Documents/references/hsa.gff3"
	mature = "/home/Documents/references/mature.fa"
	hairpin = "/home/Documents/references/hairpin.fa"
	genome = "GRCh38"

	protocol = "qiaseq"
	fastp_min_length = 15

  	profiles {
	  debug {
	    cleanup = false
	  }
	}
}

**Comment by apeltzer** [comment]
This entirely depends on the sequence of UMIs you're using. The reads are dedupped before the UMis are removed, then extracted and added to the fastq header. This is what I used with some QIAGEN miRNA UMI data:

```bash
nextflow run nf-core/smrnaseq \
    --input Samplesheet.csv \
    --outdir 01_smrnaseq \
    --genome GRCh38 -profile yourprofile\
    --mirtrace_species "hsa" \
    --skip_mirdeep \
    --protocol "qiaseq" \
    --umitools_extract_method regex \
    --umitools_bc_pattern '.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)' \
    --save_umi_intermeds \
    --with_umi \
    -c extra_resources.config \
    -resume
```

**Comment by apeltzer** [comment]
This is weird: 

![image](https://github.com/nf-core/smrnaseq/assets/2359510/cf0f0212-1fff-4daa-8e11-cf2f744d878a)

And the reason is that you should just supply the pattern, not an additional "=" in between. 
```bash
--umitools_bc_pattern = '.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=....
```

Should be:
```
--umitools_bc_pattern '.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)'
```

I'll close this as this should be fine

**Comment by genesandbones** [comment]
Thanks, this does seem to work, though now I'm getting the mirtrace error that others have (see #262).

Also, the umitools_bc_pattern code I used came from the intro page of smrna seq so this should probably be edited to reflect the suggestion above: 
![image](https://github.com/nf-core/smrnaseq/assets/38194037/9c3ffde8-695e-4b62-a3fb-725c27f12b0d)
Thanks for your help!
