### ISSUE TITLE
--three_prime_adapter set to "" gives an error

### ISSUE THREAD

**Issue by chunxuan-hs** [nf-core/smrnaseq#326]
### Description of the bug

I am trying to use 'custom' and let `fastp` to autotect the adapter. According to doc (v2.3.0)

> At least the custom protocol has to be specified, otherwise the pipeline won’t run. In case you specify the custom protocol, ensure that the parameters above are set accordingly or the defaults will be applied. If you want to auto-detect the adapters using fastp, please set --three_prime_adapter to "".

However, the pipelien gives the following error:
`--three_prime_adapter: expected type: String, found: Boolean (true)`

Could you look into it? Many thanks!

### Command used and terminal output

```console
/opt/nextflow/nextflow run /opt/nf_core_pipeline/nf-core-smrnaseq_2.3.0/2_3_0 \
    --input samplesheet.csv \
    --protocol 'custom' \
    --outdir nf_core_smallRNA_res \
    --fasta genome_resources/ensembl/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz \
    --mirna_gtf nf_core/small_RNA/mirbase/hsa.gff3 \
    --mirtrace_species 'hsa' \
    --three_prime_adapter '' \
    --filter_contamination \
    --rrna nf_core/small_RNA/silva/expert_dbSILVA_AND_TAXONOMY9606_AND_entry_typeSequence.fasta \
    --trna f_core/small_RNA/gtrnadb/hg38-tRNAs.fa \
    --cdna nf_core/small_RNA/Homo_sapiens.GRCh38.cdna.all.fa \
    --ncrna nf_core/small_RNA/Homo_sapiens.GRCh38.ncrna.fa \
    -profile singularity \
    --save_reference
```

### System information

nextflow version:
N E X T F L O W  ~  version 23.10.0
Linux, Ubuntu 22.04

**Comment by christopher-mohr** [comment]
Hi @chunxuan-hs, thanks a lot for reporting. This should be fixed now in `dev` branch. Can you test it again?

**Comment by christopher-mohr** [comment]
Closed due to lack of feedback. Please reopen if the problem persists.
