### ISSUE TITLE
mirtrace casting error - with a fix

### ISSUE THREAD

**Issue by seiboldfyr** [nf-core/smrnaseq#327]
### Description of the bug

Our pipeline errors out with a casting error when entering mirtrace in version 2.3 (and dev version) of the smRNAseq pipeline. It works fine with only fastp adapter trimming, but when we use the UMI tools and fastp we consistently get the java type casting bug. 

The fix is: edit the smrnaseq/modules/local/mirtrace.nf file, line 10. The pipeline uses `path(reads)`, but when that's changed to `val(reads)` the pipeline completes without the casting bug. Verifies that it removes UMIs and adapters as expected as well.

### Command used and terminal output

```console
input: 

nextflow run nf-core/smrnaseq -profile docker -r dev -c ${inputConfig} --input ${inputFile} --outdir '.' -work-dir './work/' --genome GRCh38 --mirtrace_species 'hsa' --with_umi true --umitools_extract_method regex --umitools_bc_pattern '.+(?P<discard_1>AACTGTAGGCACCATCAAT){s<=2}(?P<umi_1>.{12})(?P<discard_2>.*)' --save_umi_intermeds true --protocol 'qiaseq' --fastp_min_length 15


output: 

ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:MIRTRACE:MIRTRACE_RUN (1)'

Caused by:
  Cannot cast object 'qiaseq_Adeptlinear.fastp.fastq.gz' with class 'nextflow.processor.TaskPath' to class 'java.util.List' -- Check script '/home/fyrseq/.nextflow/assets/nf-core/smrnaseq/./workflows/../subworkflows/local/../../modules/local/mirtrace.nf' at line: 28

Source block:
  def primer = adapter ? "--adapter ${adapter}" : ""
  def protocol = params.protocol == 'custom' ? '' : "--protocol $params.protocol"
  def java_mem = ''
  if(task.memory){
          tmem = task.memory.toBytes()
          java_mem = "-Xms${tmem} -Xmx${tmem}"
      }
  def config_lines = [ids,reads]
      .transpose()
      .collect({ id, path -> "echo '${path},${id}' >> mirtrace_config" })
```

### Relevant files

[nextflow.log](https://github.com/nf-core/smrnaseq/files/14563152/nextflow.log)

### System information

* smRNAseq version dev (also tested with 2.3.0)
* Nextflow version: 23.10.1.5891
* Java version: openjdk version "11.0.22" 2024-01-16
* Operating system: Linux
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by apeltzer** [comment]
https://github.com/nf-core/smrnaseq/blob/c611b15e973999368a6d44dcee3f26c3e392358f/modules/local/mirtrace.nf#L10 

I can't find the issue here...?

**Comment by seiboldfyr** [comment]
Ah sorry, I switched the words! Meant to say that `path(reads)` errors, but `val(reads)` works. Just corrected my post.

**Comment by apeltzer** [comment]
Does that then work for multiple samples too?

**Comment by seiboldfyr** [comment]
Yes, we ran it on a set of 4 Qiaseq samples

**Comment by apeltzer** [comment]
Please run with `-r dev` or soon `-r 2.3.1` - this should be fine then
