### ISSUE TITLE
Documentation and code don't match for 'cats' protocol

### ISSUE THREAD

**Issue by KevinMenden** [nf-core/smrnaseq#33]
Hi,

just found a tiny issue - the adapter sequence for the 'cats' protocol in the code and in the documentation don't match. It's uncommented in the code, see line 107 in main.nf

Small issue but can lead to some frustration I imagine.

Cheers,
Kevin

**Comment by lpantano** [comment]
If you have the PR, go ahead, it should say something like this under the adapter column, that way it appears at your contribution directly :)

`AAAAAAAAAAA + GATCGGAAGAGCACACGTCTG (only polyA is used for trimming)`

**Comment by KevinMenden** [comment]
Well you can hardly call that a contribution, but I made the PR anyway :-) #34
