### ISSUE TITLE
mirdeep2 output missing

### ISSUE THREAD

**Issue by LucasMcNU** [nf-core/smrnaseq#330]
### Description of the bug

Running the smRNAseq pipeline does not produce the output listed [here](https://nf-co.re/smrnaseq/2.3.0/docs/output). **MirDeep2 output is missing**. Everything else is there. Running this on the [Northwestern University HPC](https://www.it.northwestern.edu/departments/it-services-support/research/computing/quest/) using their [configuration file](https://github.com/nf-core/configs/blob/master/docs/nu_genomics.md). Used the following genome file: 

`projects/genomicsshare/AWS_iGenomes/references/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa`

Command I used is below:

### Command used and terminal output

```console
## Load modules
module purge

module load nextflow/23.04.3
module load singularity/latest
module load graphviz/2.40.1
module load java/jdk11.0.10

project_dir=/projects/b1042/BackmanLab/Lucas/101823_rnaseq/Backman19_10.18.2023/smallRNA/
cd $project_dir
OUTDIR=${project_dir}nextflow_results/
[ -d $OUTDIR ] || mkdir -p $OUTDIR

nextflow run nf-core/smrnaseq \
-profile nu_genomics \
--input $project_dir/samplesheet.csv \
--genome 'GRCh38' \
--mirtrace_species 'hsa' \
--protocol 'nextflex' \
--outdir $OUTDIR
```

### Relevant files

[nextflow.log](https://github.com/nf-core/smrnaseq/files/14730037/nextflow.log)

**Comment by mazzalab** [comment]
same here

**Comment by apeltzer** [comment]
https://github.com/nf-core/smrnaseq/pull/343 fixed
