### ISSUE TITLE
bcbio-nextgen error for paired end data

### ISSUE THREAD

**Issue by vishal7245** [nf-core/smrnaseq#332]
### Description of the bug

The bug occurs due to unrecognized arguments passed to the `seqcluster` command. It expects input files in a specific format but receives unexpected arguments, causing termination with exit status 151. 

I am trying to run the pipeline of paired-end data

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq -r dev -profile singularity -params-file nf-params.json        


-[nf-core/smrnaseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (untreated_2_seqcluster)'

Caused by:
  Process `NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (untreated_2_seqcluster)` terminated with an error exit status (151)

Command executed:

  seqcluster collapse -f untreated_2_1.fastp.fastq.gz untreated_2_2.fastp.fastq.gz -m 1 --min_size 15 -o collapsed
  gzip collapsed/*_trimmed.fastq
  mkdir final
  mv collapsed/*.fastq.gz final/.
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES":
      seqcluster: $(echo $(seqcluster --version 2>&1) | sed 's/^.*seqcluster //')
  END_VERSIONS

Command exit status:
  151

Command output:
  Probably this will fail, you need bcbio-nextgen for many installation functions.
  ['collapse', '-f', 'untreated_2_1.fastp.fastq.gz', 'untreated_2_2.fastp.fastq.gz', '-m', '1', '--min_size', '15', '-o', 'collapsed']

Command error:
  Probably this will fail, you need bcbio-nextgen for many installation functions.
  ['collapse', '-f', 'untreated_2_1.fastp.fastq.gz', 'untreated_2_2.fastp.fastq.gz', '-m', '1', '--min_size', '15', '-o', 'collapsed']
  usage: seqcluster [-h] [--version] {collapse} ...
  seqcluster: error: unrecognized arguments: untreated_2_2.fastp.fastq.gz

Work dir:
  /media/vishal/345CBF8B7CA2CB42/virdb_rna/PRJNA779610/work/6b/456ad3a3e6e3fc893639e7ba2a92de

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/smrnaseq/files/14747259/default.nextflow.log)
[nf-params.json](https://github.com/nf-core/smrnaseq/files/14747260/nf-params.json)
[samples.csv](https://github.com/nf-core/smrnaseq/files/14747262/samples.csv)

### System information

Nextflow version: 23.10.1
Hardware: Desktop
Executor: Local
Container engine: Singularity
Version of nf-core/smrnaseq: dev

**Comment by savytskanatalia** [comment]
@vishal7245 have you been able to resolve it? I got the same error for my paired-end data

**Comment by lpantano** [comment]
Hi,

thank you for posting. smrnaseq is not compatible with paired data right now, it only uses the reads that is forward to the small RNA. I don't think supporting second reads is in the plan for this. Normally, this pipeline is focused to detect miRNAs, tRNA fragments and alike. So one read is enough, two reads can improve with error sequencing vs real mutations, but there are not many tools that work with paired end data.

Thanks!

**Comment by savytskanatalia** [comment]
@lpantano thank you for the reply. Could you then maybe please update "Usage" page on nf-core website?
Because currently it reads as if it is indeed possible to feed in paired-end sequencing files. And pipeline does attempt to process them by merging at the fastp step, but then instead of feeding the merged file into seqcluster collapse, it still attempts to feed a pair of trimmed uncollapsed files... I attach the screenshots below.
![image](https://github.com/nf-core/smrnaseq/assets/43849297/501ae446-0b7b-4db6-adeb-b766e9c36b21)
![image](https://github.com/nf-core/smrnaseq/assets/43849297/af8b5757-81b8-4269-8428-18fcf62a72c6)

**Comment by apeltzer** [comment]
This was clarified in the docs, therefore closing now.
