### ISSUE TITLE
how to apply the updated version

### ISSUE THREAD

**Issue by ylang0825** [nf-core/smrnaseq#338]
### Description of feature

Hello, I have a simple question about use of the latest version. Previously, I reported a bug and the developers have corrected it and merged new code into the latest version 5 days ago (I checked the code was corrected under the dev tag online). However, I tried running the software today with ‘-r dev’ and found the bug was still there. I don't know whether '-r dev' could directly get the latest dev version.

Here is my command: 
nextflow run nf-core/smrnaseq --input ./samplesheet2.csv --outdir ./results --genome GRCh38 -profile conda --mirtrace_species hsa --three_prime_adapter AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA -r dev

I also noticed that the software would have this output:
N E X T F L O W  ~  version 23.10.1
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [38b898aaf0]
Launching `https://github.com/nf-core/smrnaseq` [focused_edison] DSL2 - revision: d5910ecbe7 [dev]

Thank you!

**Comment by christopher-mohr** [comment]
Hi @ylang0825, please try running `nextflow pull nf-core/smrnaseq -r dev`.

**Comment by ylang0825** [comment]
Hi @christopher-mohr, I used this command as suggested:
nextflow pull nf-core/smrnaseq -r dev --input ./samplesheet2.csv --outdir ./results --genome GRCh38 -profile conda --mirtrace_species hsa --three_prime_adapter AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA

However, it returned another error:
Unknown option: --input=./samplesheet2.csv -- Check the available commands and options and syntax with 'help'

It's weird, as this does not happen before.

**Comment by christopher-mohr** [comment]
> Hi @christopher-mohr, I used this command as suggested: nextflow pull nf-core/smrnaseq -r dev --input ./samplesheet2.csv --outdir ./results --genome GRCh38 -profile conda --mirtrace_species hsa --three_prime_adapter AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
> 
> However, it returned another error: Unknown option: --input=./samplesheet2.csv -- Check the available commands and options and syntax with 'help'
> 
> It's weird, as this does not happen before.

Sorry for the confusion. You just have to run `nextflow pull nf-core/smrnaseq -r dev` and afterwards you run the pipeline using `nextflow run nf-core/smrnaseq -r dev... ` as before. This should then use the updated pulled pipeline version.

**Comment by ylang0825** [comment]
@christopher-mohr Thanks!
