### ISSUE TITLE
`mirdeep2` is missing from workflow outputs if `fasta` parameter is not set

### ISSUE THREAD

**Issue by BWMac** [nf-core/smrnaseq#359]
### Description of the bug

The `mirdeep2` directory is missing from the output directory if `fasta` is not specified in the workflow parameters. I was able to get the `mirdeep2` folder to populate in the results directory by providing the `fasta` parameter in addition to the `genome` parameter. If I am understanding the workflow correctly `fasta` is not supposed to be required if the `genome` is provided. 

The problem appears to be this [line](https://github.com/nf-core/smrnaseq/blob/5901bea438cb719c186f883bb6e6a11f1de70a5b/workflows/smrnaseq.nf#L209) of the workflow where if `params.fasta` is not specified these processes are skipped. My guess is that the idea was for this to not be an issue because of this [line](https://github.com/nf-core/smrnaseq/blob/5901bea438cb719c186f883bb6e6a11f1de70a5b/main.nf#L31) where the `params.fasta` parameter is set based on the workflow, but Nextflow still does not recognize this parameter as being set when evaluating the logical statement.

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq -profile singularity -params-file my_params.yaml

unsuccessful my_params.yaml:
input: '/path/to/input.csv'
outdir: '/path/to/outdir'
genome: 'GRCh37'
mirtrace_species: 'hsa'
filter_contamination: true
trna: http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/hg38-tRNAs.fa
ncrna: ftp://ftp.ensembl.org/pub/release-86/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz

successful my_params.yaml:
input: '/path/to/input.csv'
outdir: '/path/to/outdir'
genome: 'GRCh37'
fasta: 's3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa'
mirtrace_species: 'hsa'
filter_contamination: true
trna: http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/hg38-tRNAs.fa
ncrna: ftp://ftp.ensembl.org/pub/release-86/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
```

### System information

Nextflow version 24.04.2
HPC
slurm
Singularity
Linux
nf-core/smrnaseq version 2.3.1

**Comment by nschcolnicov** [comment]
@BWMac Issue was fixed, was able to run the latest dev version using the params-file and command provided. Please retry and let me know. Just as a comment, I saw that you were using trna and ncrna from GRCh38, but you indicating genome GRCh37, not sure if it was just an example, but wanted to give you a heads up.  We have a profile that uses the trna, ncrna and cdna from GRCh37 in case you need it: https://github.com/nf-core/smrnaseq/blob/dev/conf/test_contamination.config

**Comment by BWMac** [comment]
@nschcolnicov Works as expected, thanks!
