### ISSUE TITLE
I have some usage issues

### ISSUE THREAD

**Issue by xfk274280** [nf-core/smrnaseq#363]
1.Is my data, which is whole transcriptome data (pair-end), suitable for this pipeline? (I noticed that in the samplesheet.csv, there's only fastq_1 mentioned.)
2.I have some doubts about the UMI (Unique Molecular Identifier) step. Is my data suitable for it?

**Comment by apeltzer** [comment]
1.) Yes, but only the R1 information will be used. R2 isnt of any value. However, if your protocol wasn't suitable for miRNA library prep, you're not going to find a lot of miRNAs if any. 
2.) If you dont know about that, you should figure out what type and library prep of data you have. Once you know this, you can make a more justified decision.
