### ISSUE TITLE
Improve pipeline tests for different protocols

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#366]
### Description of feature

Should be done in two steps: 

* Finding proper testdata that is published somewhere
* Integrating these into testData
* Using the new config profile(s) as in #364  and then testing these properly

**Comment by lpantano** [comment]
this could be an option, can you take a look and see if we can use some of these samples:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE149513

**Comment by apeltzer** [comment]
Looks like we can use these to me - lets see how easy it would be to add these to nf-core/testdatasets and then run them using the profiles. Shouldn't be too hard and we can get some proper tests then running.

**Comment by lpantano** [comment]
that would be great!

**Comment by lpantano** [comment]
as far as I know, tools need those file from miRBase, we could potentially put them nf-core test-dataset, I don't think the license is a problem. I don't see anything in their webpage that will limit that. I think the hairpin.fa is the only one in RNAcentral, but as well we will need the GFF file from miRBase and the mature.

**Comment by apeltzer** [comment]
If the licence is no problem, we can certainly dump this on S3 and use that URl.

**Comment by nschcolnicov** [comment]
PR was merged https://github.com/nf-core/smrnaseq/pull/456
