### ISSUE TITLE
Changelog mentions duplicate releases

### ISSUE THREAD

**Issue by MaxUlysse** [nf-core/smrnaseq#37]
Also according to CHANGELOG, there is already two `1.0` releases, on top on the `1.0.0`, but the `SciLifeLab/NGI-smRNAseq` has none...

I think it should be bumped to the next `dev`, and the matter of the old `1.0` should be fixed.

**Comment by ewels** [comment]
Release version now appears to be bumped in `dev`, but the changelog should definitely only mention the main nf-core releases, so that needs cleaning up..
