### ISSUE TITLE
Update Docs & Consistency checks

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#370]
### Description of feature

Docs should be updated and consistency checked to match pipeline

**Comment by atrigila** [comment]
I am going to add here the changes that we could do related to style and syntax according to the new specifications. 

Major:
- There are instances of params being used inside subworkflows or modules. They should be replaced by their corresponding channels.
- Params should be defined in the pipeline initialisation workflow. This workflow should emit channels that can be passed to the main smrnaseq workflow
- Params cannot be used outside the entry workflow

Minor:
- Apply nf-core naming conventions for local modules/subworkflows
- Input channel name should signify structure with the input object type
- Each input and output channel should have a comment describing the output structure of the channel
