### ISSUE TITLE
Assess converting local modules to nf-core

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/smrnaseq#392]
The scope of this ticket is to assess:
Which modules could already be replaced by nf-core ones, with or without minimal changes to config or workflow files.
Which modules could be updated to become an nf-core module.

And on a second step, to implement these changes.

FYI @atrigila @apeltzer @grst

**Comment by apeltzer** [comment]
Makes sense - please do not overinvest. If there are easy ones - yes go ahead, if there are debatable ones --> assess nd keep for now, some might be difficult / overinvestment and in such cases we should keep them local only 👍🏻
