### ISSUE TITLE
Use bowtie 1 for human genome alignment

### ISSUE THREAD

**Issue by ewels** [nf-core/smrnaseq#4]
Moved from https://github.com/SciLifeLab/NGI-smRNAseq/issues/3

---

Probably shouldn't have put Bowtie 2 into the latest change.

Need to read this paper and take on advice:
http://bib.oxfordjournals.org/content/16/6/950.full

> Alignments performed using Bowtie 2 resulted in an even greater number of miRNAs with higher counts; examination of the alignment output revealed that many of these were attributed to the allowance of insertions and deletions.
> 
> Bowtie 2, which was developed for gapped alignment, was included in our comparison to illustrate the consequences of selecting an inappropriate aligner.

----
@zhenyisong:
There is another paper regarding the same issue, "Evaluation of microRNA alignment techniques". PMID: 27284164.

**Comment by chuan-wang** [comment]
Fixed in PR https://github.com/nf-core/smrnaseq/pull/9
