### ISSUE TITLE
Error in the edgeR_mirna process

### ISSUE THREAD

**Issue by lcabus** [nf-core/smrnaseq#40]
Hi! I was trying to run this pipeline with some miRNA data, but I encountered the following error.

Error executing process > 'edgeR_mirna' 

Caused by: 
  Process `edgeR_mirna` terminated with an error exit status (1)

Command executed:

  edgeR_miRBase.r Plasma_S1_L001_R2_001.hairpin.stats Plasma_S1_L001_R2_001.mature.stats Plasma_S1_L001_R1_001.mature.stats Plasma_S1_L001_R1_001.hairpin.stats

Command exit status:
  1

Command output:
  $mature
  [1] "Plasma_S1_L001_R2_001.mature.stats" "Plasma_S1_L001_R1_001.mature.stats"
  
  $hairpin
  [1] "Plasma_S1_L001_R2_001.hairpin.stats" "Plasma_S1_L001_R1_001.hairpin.stats"

Command error:
  Loading required package: limma
  Loading required package: edgeR
  Loading required package: statmod
  Loading required package: data.table
  Loading required package: gplots
  
  Attaching package: ‘gplots’
  
  The following object is masked from ‘package:stats’:
  
      lowess
  
  Error in quantile.default(x, p = p) : 
    missing values and NaN's not allowed if 'na.rm' is FALSE
  Calls: calcNormFactors ... .calcFactorQuantile -> apply -> FUN -> quantile -> quantile.default
  In addition: Warning message:
  In DGEList(counts = data, genes = rownames(data)) :
    library size of zero detected
  Execution halted

I use the pipeline with this configuration:
`` nextflow run nf-core/smrnaseq --reads '*{1,2}.fastq.gz' --genome GRCh37 -profile singularity ``

How can I solve this?

**Comment by lpantano** [comment]
Hi,

I don’t know if it is related, but this pipeline only works with singleEnd
reads. And there is an existing error when only one sample is going through
the pipeline as far I remember.

sorry.

**Comment by lluccabus** [comment]
Okay, I suppose that was the problem then.

Thank you

**Comment by lluccabus** [comment]
Hi,
I'm sorry that I closed the issue and have to reopen it again.

I tried again with 3 samples with singleEnd reads and the error remains, it happens in the ``edgeR_miRBase.r``.

I post the .command.err:

Loading required package: limma
Loading required package: edgeR
Loading required package: statmod
Loading required package: data.table
Loading required package: gplots

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

**Error in quantile.default(x, p = p) :
  missing values and NaN's not allowed if 'na.rm' is FALSE
Calls: calcNormFactors ... .calcFactorQuantile -> apply -> FUN -> quantile -> quantile.default**
In addition: Warning message:
In DGEList(counts = data, genes = rownames(data)) :
  library size of zero detected
Execution halted

The bold part is what is causing the error, but I don't know what is happening there.

Thank you

**Comment by lpantano** [comment]
Hum, normally I got into the working directory and run one by one line the
scripts to see what is the issue. If you can send me the input files you
see in that folder I can try to reproduce. It seems the miRNA
quantification is not working properly :s

**Comment by lluccabus** [comment]
Hi,
After some digging I found that there was a file giving some problems, after getting rid of this file everything worked fine.

Thanks
