### ISSUE TITLE
Improve the contaminant filter

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#406]
Contaminant filter has several issues that can be improved, among them:
- The code has repetitive blocks for each contaminant type (e.g., cdna, ncrna, pirna, etc.) that can be refactored into function/processes.
- There are still several modules that are local instead of nf-core ones

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by apeltzer** [comment]
At least the latter point has been solved now.
