### ISSUE TITLE
Add takarabio SMARTer smRNA-Seq Kit profile option

### ISSUE THREAD

**Issue by mlist** [nf-core/smrnaseq#43]
This could be a useful addition for the profiles, which could be named 'smart', for instance.

In their [documentation](https://www.takarabio.com/assets/documents/User%20Manual/SMARTer%20smRNA-Seq%20Kit%20for%20Illumina%20User%20Manual_121219.pdf
), Takara provides settings for cutadapt which I think translate to the following settings in trimgalore config for the pipeline:

```
min_length = 15
clip_R1 = 3
three_prime_adapter = 'AAAAAAAAAA'
```

I will test these settings and report if this works...

**Comment by apeltzer** [comment]
Its entirely possible to specify this in the pipeline now freely - e.g. `nextflow run nf-core/smrnaseq -r 2.0.0 --min_length 15 --clip_r1 3 --three_prime_adapter 'AAAAAAAAAA'` should do the trick for you 👍🏻
