### ISSUE TITLE
Problems with miRTrace output

### ISSUE THREAD

**Issue by lcabus-flomics** [nf-core/smrnaseq#44]
Hi,
I was running the pipeline with 40 samples and everything worked well, but at the end I didn't obtain the mirtrace files (mirtrace-report.html, mirtrace-results.json, etc.), I only obtained the qc_passed_reads.all.collapsed and qc_passed_reads.rnatype_unknown.collapsed.
Nonetheless, the pipeline was completed successfully and I think that there are no other errors. When I run the pipeline only with 10 samples everything seems to work well, I don't know which can be the problem...

Thank you very much!

**Comment by shashwatsahay** [comment]
This used to happen with me, were you running on a cluster if yes then you should in the cluster config file, assign more memory to processes

**Comment by lcabus-flomics** [comment]
Hi, I tried assigning more memory in general and specifically in the miRTrace process, but it still failed. I finally installed miRTrace and run it that way, but still the problem is still there. How many memory did you use? I have a put as a maximum amount of resources 200GB and 16 cpus.

**Comment by shashwatsahay** [comment]
Can you share the log files?
it would be something like .nextflow.log

**Comment by lcabus-flomics** [comment]
Hi, sorry, I was doing some tests and I had to rerun the pipeline.

[nextflow.log](https://github.com/nf-core/smrnaseq/files/4381822/nextflow.log)

in the .command.log in the miRTrace work dir I have:
_miRTrace version 1.0.0 starting. Processing 40 sample(s)._

The .command.err contains exactly the same:
_miRTrace version 1.0.0 starting. Processing 40 sample(s)._

**Comment by apeltzer** [comment]
This should nowadays not be an issue at all anymore - please give things a try (if you can / still want to) using `-r dev`.
