### ISSUE TITLE
Analysis of Paired-end reads

### ISSUE THREAD

**Issue by oliverdesousa** [nf-core/smrnaseq#440]
Hi, I am trying to run the pipeline using the paired-end miRNA reads given to me for analysis. I have used the below structure for my CSV file for the input. 

sample, fastq_1, fastq_2
clone1, path/to/fwd/read/clone1_1.fastq.gz, path/to/rvs/read/clone1_2.fastq.gz
...

When I have attempted to run with the below command it provides an error when running miRtrace. The error seems to be a problem with the input miRtrace is receiving - "ERROR ~ Unknown method invocation getFileName on ArrayList type". The custom config I have just has memory and CPU specifications. 

sudo nextflow run nf-core/smrnaseq 
  -profile singularity \
  --input test_38.csv \
  --genome 'GRCh38' \
  --mirtrace_species 'hsa' \
  --protocol 'illumina' \
  --outdir pipe_output/ \
  -c nextflow.config

Is there something i am doing wrong when trying to run paired-end reads or is there a specific way to do this?

**Comment by apeltzer** [comment]
Just as a side node to some of the points you mentioned there:

* The pipeline should only use SE data, not PE - the read length of a SE read is already longer than what we target to analyze - the fastq_2 is therefore not considered
* There is an open PR https://github.com/nf-core/smrnaseq/pull/439 that fixes some feedback / handles some logic errors, will be in `dev` very soon
* If you use `-r dev` to run the pipeline and remove the fastq_2 entries, the pipeline should already run fine

And please don't run the pipeline with sudo, this is not necessary and if it does, there should be some misconfiguration happening on your system. 

If the problem persists, please let us know and re-open the issue.
