### ISSUE TITLE
Make citation tools dependent on whether tool was executed 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#468]
OMG ever since I added this I think this is the first time I've seen someone else use it :star_struck: .

Do all tools get used by default? If some are optional you can also specify each tool with a condition e.g. `params.run_<tool> ? <ref> : ''`

_Originally posted by @jfy133 in https://github.com/nf-core/smrnaseq/pull/446#discussion_r1790212290_

**Comment by jfy133** [comment]
See taxprofiler for a (complex) example :)

Note this is a minor one and not a blockwr for the release.
