### ISSUE TITLE
adding coreutils/realpath 

### ISSUE THREAD

**Issue by bazelep** [nf-core/smrnaseq#48]
Hello,
When I run nf-core/smrnaseq revision 1.0.0 the mirtrace steps fail due to missing "realpath" command. Could perhaps coreutils be added to the conda environment for installation?
Thank you,
Peter Bazeley

**Comment by apeltzer** [comment]
Hi @bazelep - looking at the documentation of mirtrace, there is no listing that coreutils would be required for running mirtrace at all. Can you share more information (or rerun with the latest `-r dev` branch to check if this is resolved?) 

Thanks!

**Comment by bazelep** [comment]
Hi @apeltzer, 
The issue I had was a call to the "realpath" UNIX utility, which wasn't in my PATH at the time and so I edited the main.nf file to include the full path. It has been awhile since I used the smrnaseq workflow and perhaps the issue is fixed. Feel free to close this.
Regards,
Peter

**Comment by apeltzer** [comment]
Ok, will do so - if you at some point encounter the issue again, please re-open.
