### ISSUE TITLE
No Reference genome availabe in miRBase and MirGeneDB

### ISSUE THREAD

**Issue by sajjadasaf** [nf-core/smrnaseq#487]
I want to run the smrnseq pipeline for a plant species whose genome is not available in miRBase or miRGeneDB. Can you guide me on whether it is possible to use this pipeline for such genomes? I am new to nf-core.

**Comment by apeltzer** [comment]
If you want to work on this, feel free to open a PR on the matter. We're currently not having capacity to work on this unfortunately :-(
