### ISSUE TITLE
update help text for fasta parameter

### ISSUE THREAD

**Issue by kopichris** [nf-core/smrnaseq#491]
### Description of the bug

The help text for the `--fasta` parameter asserts that this parameter is required if `--genome` is not specified; however, the pipeline can function properly without specifying either parameter.  Setting either parameter should only be required for genome quantification (optional) and identification of miRNAs using `miRDeep2` (optional).  The help text also mentions the use of a BWA index, but I believe it should be changed to a Bowtie1 index.

### Command used and terminal output

```console
Help text (fasta): This parameter is mandatory if --genome is not specified. If you don't have a BWA index available this will be generated for you automatically. Combine with --save_reference to save BWA index for future runs.
```

**Comment by atrigila** [comment]
Closed via #494
