### ISSUE TITLE
Add option for sequencing centre in BAM file

### ISSUE THREAD

**Issue by ewels** [nf-core/smrnaseq#6]
Moved from https://github.com/SciLifeLab/NGI-smRNAseq/issues/35

---

## Bowtie 1
Output options:
`--sam-RG <text>`
Add `<text>` (usually of the form `TAG:VAL`, e.g. `ID:IL7LANE2`) as a field on the `@RG` header line. Specify `--sam-RG` multiple times to set multiple fields.
`--sam-RG` is ignored unless `-S`/`--sam` is also specified.

## Bowtie2

SAM options: `--rg <text>`

Add `<text>` (usually of the form `TAG:VAL`, e.g. `SM:Pool1`) as a field on the `@RG` header line.

e.g.:
```
--rg CN:nameofourgroup
```

**Comment by chuan-wang** [comment]
The default output format from Bowtie 1 is flat text. Therefore we will need the `-S` option to generate sam/bam files. Unfortunately it is conflict with the option `--sam-RG`.
