### ISSUE TITLE
Make sample name cleaning regex configurable

### ISSUE THREAD

**Issue by ewels** [nf-core/smrnaseq#64]
A bunch of steps in the pipeline attempt to clean off common filename suffixes to give nicer sample names, eg:

https://github.com/nf-core/smrnaseq/blob/a115116a06ad274b475834316d0193e1b756b249/main.nf#L428

1. `(.R1)?` should probably be `(\.R1)?` as the `.` alone is a wildcard matching any character
2. This regex should be kept as a `params` variable to avoid repeating, and to make it configurable by the end user if it's having an undesirable effect.

**Comment by atrigila** [comment]
The code has undergone significant changes since this issue was raised, and this specific line no longer exists. Additionally, the regex configuration is now handled via MultiQC :)
