### ISSUE TITLE
SMrnaseq: Convert usage docs to JSON schema 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#70]
Hi!

this is not necessarily an issue with the pipeline, but in order to streamline the documentation group next week for the hackathon, I'm opening issues in all repositories / pipeline repos that might need this update to switch from parameter docs to auto-generated documentation based on the JSON schema.

This will then supersede any further parameter documentation, thus making things a bit easier :-)

If this doesn't apply (anymore), please close the issue. Otherwise, I'm hoping to have some helping hands on this next week in the documentation team on Slack https://nfcore.slack.com/archives/C01QPMKBYNR

**Comment by ewels** [comment]
@ErikDanielsson - this is another good one for you. Use `nf-core schema build .` to create and customise a schema (can run it as many times as you like). You then need to copy out the existing descriptions / help text from the `main.nf` cli help text and `usage.md`. Then delete all of the parameter docs from those two files.

Bit fiddly, but mostly copy and paste 👍🏻

**Comment by ewels** [comment]
I take it back sorry, this is already done on `dev`. Can see the docs here: https://nf-co.re/smrnaseq/dev/parameters
