### ISSUE TITLE
--max_cpus default value overrides

### ISSUE THREAD

**Issue by zeehio** [nf-core/smrnaseq#76]
This line:

https://github.com/nf-core/smrnaseq/blob/a115116a06ad274b475834316d0193e1b756b249/nextflow.config#L132

Combined with:

https://github.com/nf-core/smrnaseq/blob/a115116a06ad274b475834316d0193e1b756b249/conf/base.config#L43

Makes it that when I run the pipeline with a `nextflow.config` like:

```
process {
    cpus = 25
    memory = 500.GB
}
```

The limit is still 16 cores.

Should I then specify the limit twice for it to be applied to this pipeline?

**Comment by KevinMenden** [comment]
Hi @zeehio, the base config overwrites the stuff in the nextflow config ( I think :thinking: )

So alternative would be to make an extra little config `my_config.config` , put that process definition in there and load it with `-c my_config.config` when running the pipeline. 
The other alternative would be to use `--max_cpus 25` when running the pipeline, that should overwrite it, too.

Sorry for the late reply, this pipeline has not gotten much love lately - if you check the slack channel you'll get answers within minutes or hours :)
