### ISSUE TITLE
Cannot change Trimgalore max_length parameter

### ISSUE THREAD

**Issue by DwinGrashof** [nf-core/smrnaseq#77]
When investigating other smallRNAs one might want to increase the max_length of trimgalore, so that reads > 40bp are not thrown out. However, this is not possible in the current 1.,0.0 version of the smrnaseq pipeline. In the main.nf script the `max_length` is hardcoded as 40 bp into the script, making it impossible to change this parameter.

I changed the hardcoded bit of trimgalore, and added a parameter that can be assigned in the config file, trying to mimic the syntax and style of the `min_length` parameter. Please mind that there is no "default" in the adapted script. This could very well be added as 40 bp in the future so people won't experience changes when rerunning the pipeline.

I have trouble with creating a branch/PR, so if one of the devs could help me with that, that would be amazing.

**Comment by KevinMenden** [comment]
Thanks for reporting @DwinGrashof , I'll have a look at it! :+1:
