### ISSUE TITLE
missing mirtop results

### ISSUE THREAD

**Issue by LucaGiudice** [nf-core/smrnaseq#99]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/smrnaseq pipeline documentation](https://nf-co.re/nf-core/smrnaseq/usage)

## Description of the bug

I recently applied the pipeline to my miRNAseq data and I was particularly interested into mirtop results.
However, the pipeline does not produce either the mirtop results or the results/mirtop directory.
In other words, the step "miRNA and isomiR annotation from step 4.1 (mirtop)" seems missing. 
I also checked the "Nextflow workflow report" produced by the pipeline and the step of mirtop is not included in the execution. It does not appear in the legend of tasks and it does not have a running time or memory usage.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: [nextflow run nf-core/smrnaseq -r 1.1.0 --input '/storage_1/fastq2_small/\*_N_*.fastq.gz' -profile docker --protocol custom --genome GRCm38 --clip_r1 0 --three_prime_clip_r1 0 --max_cpus 30 --three_prime_adapter AGATCGGAAGAGCACACGTCT --mirtrace_protocol Illumina]

## Expected behaviour

The results/mirtop directory with isomiR annotation.

## Log files

Have you provided the following extra information/files:

- [X] The command used to run the pipeline

## System

- Hardware:  [Desktop] 
- Executor: [local] 
- OS: [Ubuntu 18.04.5 LTS]

## Container engine

- Engine: [Docker]
- version: [1.1.0]
- Image tag: [e.g. nfcore/smrnaseq:1.1.0]

Thank you for your future reply.

**Comment by lpantano** [comment]
Hi, 

Thank you for the report, I dealt with that a few weeks ago, working on some enhancement besides this before creating the PR. Did you try to pass `--mirna_gtf` with the expected file: `ftp://mirbase.org/pub/mirbase/CURRENT/genomes/hsa.gff3`, that worked for me in the mean time.

Thanks for reporting!

**Comment by LucaGiudice** [comment]
I applied the pipeline with the following command: run nf-core/smrnaseq -r 1.1.0 --input '/storage_1//N/4*.fastq.gz' -profile docker --protocol custom --genome GRCm38 --clip_r1 0 --three_prime_clip_r1 0 --max_cpus 10 --three_prime_adapter AGATCGGAAGAGCACACGTCT --mirtrace_protocol illumina --mirna_gtf ftp://mirbase.org/pub/mirbase/CURRENT/genomes/mmu.gff3

As result, I have obtained the mirtop directory and files. However, the files are empty except for their headers.  Even the mirtop.gff file is empty:
  mirGFF3. VERSION 1.2
  source-ontology: miRBasev22 doi:10.25504/fairsharing.hmgte8
  TOOLS: BAM
  COLDATA: 439_N_N252-366_S19_ME_L001_R1_001

is it actually possible to get no results? 
the data have a good quality, the pipeline detects 1500 mature miRNAs and also mirdeep is able to catch dozens of novel miRNAs.

**Comment by lpantano** [comment]
Indeed that is weird. Could you get the logs from running mirtop? If not I would run it locally that step to get the logs and check. I can take a look at the logs and see if the error is clear. If not, if you could share the bam file and the GFF file I could try to debug in a few days.

**Comment by LucaGiudice** [comment]
I am sending you one fasta sequence, the nextflow pipeline report, and the mirtop files with https://transfer.sh/
From the nextflow pipeline report, you should be able to exactly replicate the issue.
The fasta sequence is the one that I used to test the pipeline and produced zero results with mirtop.
I suggest you duplicate the fasta sequence in order to run the nextflow pipeline with seq1.fastq.gz and seq2.fastq.gz, this is why I noticed that if you run the pipeline with only one sequence you don't get the proper quantification of the miRNAs in the edgeR step. 
Link: https://transfer.sh/1JAEz7s/data.7z
The gff is this one: ftp://mirbase.org/pub/mirbase/CURRENT/genomes/mmu.gff3

**Comment by lpantano** [comment]
sadly my computer has transfer blocked so I cannot get that file. It is google drive an option?

**Comment by LucaGiudice** [comment]
I sent you the link from which you can download the data through email.
The link will be valid for two weeks, so you should not have any problem with the time limit.

**Comment by lpantano** [comment]
thank you! can you tell me what email did you use and from where it will come? I didn't find anything. Thanks!

**Comment by LucaGiudice** [comment]
lpantano@iscb.org
object: mirtop nextflow error data
from: luca.giudice@univr.it

**Comment by lpantano** [comment]
Hi, I looked twice for that email. My email is correct, but I cannot find it anywhere. Can you send it again, or maybe to lorena.pantano gmail dot com

**Comment by LucaGiudice** [comment]
Sent it with the object "mirtop smallRNA nextflow error"

**Comment by apeltzer** [comment]
`dev` contains now the new DSL2 reimplementation - please re-open if this doesn't resolve your issue(s) 👍🏻
